const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
async function context(){const elements=new Map();const el=()=>({value:'',hidden:false,textContent:'',innerHTML:'',classList:{toggle(){}},contains(){return false},getContext(){return{}},showModal(){},close(){},addEventListener(){}});let saved;const c=vm.createContext({crypto:require('node:crypto').webcrypto,structuredClone,TextEncoder,TextDecoder,Uint8Array,Date,Set,JSON,indexedDB:new (require("fake-indexeddb").IDBFactory)(),qrcode:require('../dist/vendor/qrcode.js'),console,setTimeout,clearTimeout,alert(){},confirm(){return true},document:{querySelector(s){if(!elements.has(s))elements.set(s,el());return elements.get(s)},querySelectorAll(){return[]},createElement:el,addEventListener(){}},window:{addEventListener(){},print(){}},navigator:{},localStorage:{getItem(){return null},setItem(k,v){saved=v}},btoa,atob});for(const f of ['sync-model.js','storage.js','invitations.js','app.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/'+f),'utf8'),c);vm.runInContext('function refreshSyncStatus(){};function scheduleSync(){};',c);await vm.runInContext('TemuStore.init(()=>db)',c);vm.runInContext('readFailed=false;',c);return c;}
test('Check-in berulang dan jumlah berlebih ditolak; data tetap konsisten',async()=>{const c=await context();await vm.runInContext(`(async()=>{await commit(d=>d.guests.push({id:'g',code:'c',name:'Tamu Uji',group:'',quota:2,arrived:0,active:true}));await checkIn('g',1);await checkIn('g',1);})()`,c);assert.equal(vm.runInContext('db.guests[0].arrived',c),2);await assert.rejects(vm.runInContext("checkIn('g',1)",c));assert.equal(vm.runInContext('db.logs.length',c),2);});
test('Undangan nonaktif dan jumlah negatif ditolak',async()=>{const c=await context();await vm.runInContext(`(async()=>{await commit(d=>d.guests.push({id:'g',code:'c',name:'Tamu',group:'',quota:2,arrived:0,active:false}));})()`,c);await assert.rejects(vm.runInContext("checkIn('g',1)",c));await assert.rejects(vm.runInContext("checkIn('g',-1)",c));});
test('Hapus tamu membatalkan QR dan menghapus identitas tanpa menghilangkan riwayat hadir',async()=>{const c=await context();await vm.runInContext("commit(d=>d.guests.push({id:'g',code:'lama',name:'Tamu Uji',phone:'6281234567890',group:'Keluarga',quota:2,arrived:0,active:true}))",c);await vm.runInContext("removeGuest('g')",c);assert.equal(vm.runInContext('db.guests.length',c),0);await vm.runInContext("commit(d=>d.guests.push({id:'h',code:'lama2',name:'Tamu Hadir',phone:'628999999999',group:'Teman',quota:2,arrived:0,active:true}))",c);await vm.runInContext("checkIn('h',1)",c);await vm.runInContext("removeGuest('h')",c);assert.equal(vm.runInContext('db.guests[0].name',c),'Tamu dihapus');assert.equal(vm.runInContext('db.guests[0].phone',c),'');assert.equal(vm.runInContext('db.guests[0].active',c),false);assert.equal(vm.runInContext('db.logs.length',c),1);await assert.rejects(vm.runInContext("checkIn('h',1)",c));});
test('Tombol hapus pada daftar meminta konfirmasi di aplikasi sebelum mengubah data',async()=>{const c=await context();vm.runInContext("document.querySelector('#filter').value='all'",c);await vm.runInContext("commit(d=>d.guests.push({id:'g',code:'qr',name:'Tamu Uji',phone:'',group:'',quota:1,arrived:0,active:true}))",c);assert.match(vm.runInContext("document.querySelector('#guest-list').innerHTML",c),/data-action="delete"/);vm.runInContext("showDeleteGuest('g')",c);assert.match(vm.runInContext("document.querySelector('#modal-body').innerHTML",c),/Ya, hapus tamu/);assert.equal(vm.runInContext('db.guests.length',c),1);await vm.runInContext("document.querySelector('#confirm-delete-guest').onclick({currentTarget:{disabled:false}})",c);assert.equal(vm.runInContext('db.guests.length',c),0);});
test('Pencarian tanpa QR selalu menampilkan pilihan nama dan kelompok sebelum check-in',async()=>{const c=await context();await vm.runInContext("commit(d=>d.guests.push({id:'g1',code:'qr1',name:'Bayu',group:'OJK',quota:1,arrived:0,active:true},{id:'g2',code:'qr2',name:'Bayu',group:'Keluarga CPP',quota:2,arrived:0,active:true},{id:'g3',code:'qr3',name:'Bayu Pratama',group:'Teman',quota:1,arrived:0,active:true}))",c);vm.runInContext("lookupName('bayu')",c);const results=vm.runInContext("document.querySelector('#modal-body').innerHTML",c);assert.match(results,/Bayu/);assert.match(results,/OJK/);assert.match(results,/Keluarga CPP/);assert.match(results,/Bayu Pratama/);assert.equal((results.match(/data-id=/g)||[]).length,3);assert.match(vm.runInContext("document.querySelector('#modal-title').textContent",c),/Pilih nama tamu/);vm.runInContext("lookupName('bayu pratama')",c);assert.match(vm.runInContext("document.querySelector('#modal-body').innerHTML",c),/data-id="g3"/);assert.match(vm.runInContext("document.querySelector('#modal-title').textContent",c),/Pilih nama tamu/);vm.runInContext("document.querySelector('#name-results').onclick({target:{closest:()=>({dataset:{id:'g1'}})}})",c);assert.match(vm.runInContext("document.querySelector('#modal-title').textContent",c),/Undangan terverifikasi/);});
test('Cetak QR memakai sembilan kartu per halaman landscape tanpa menampilkan ID',async()=>{const c=await context();const result=vm.runInContext("(()=>{const gs=Array.from({length:10},(_,i)=>({id:'id-'+i,code:'secret-'+i,name:'Bayu '+i,group:'',quota:i===0?2:i===1?3:1,arrived:0,active:true}));return printMarkup(gs)})()",c);assert.equal((result.match(/class="print-sheet"/g)||[]).length,2);assert.equal((result.match(/class="print-card"/g)||[]).length,10);assert.match(result,/Bayu 0 &amp; Pasangan/);assert.match(result,/Bayu 1 &amp; Keluarga/);assert.doesNotMatch(result,/id-0|secret-0/);assert.match(result,/#foREVArwithCESAR/);assert.match(result,/jangan lupa dibawa QR ini ya😉/);const css=fs.readFileSync(path.join(__dirname,'../dist/style.css'),'utf8');assert.match(css,/@page\{size:A4 landscape/);assert.match(css,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);});
test('Tombol hapus semua tamu berada di Pengaturan',()=>{const html=fs.readFileSync(path.join(__dirname,'../dist/index.html'),'utf8');const guestSection=html.slice(html.indexOf('<section id="tamu"'),html.indexOf('<section id="pengaturan"'));const settingsSection=html.slice(html.indexOf('<section id="pengaturan"'));assert.doesNotMatch(guestSection,/id="delete-all-guests"/);assert.match(settingsSection,/id="delete-all-guests"/);});
test('Operasi lama tidak dapat mengembalikan tamu setelah penghapusan massal',async()=>{const c=await context();const result=vm.runInContext("(()=>{const before=fresh();before.guests.push({id:'g',code:'qr',name:'Tamu',group:'',quota:1,arrived:0,active:true});const after=structuredClone(before);after.guests[0].arrived=1;const op=TemuModel.operation(before,after);const cleared=structuredClone(before);cleared.guests=[];cleared.guestEpoch=1;try{TemuModel.apply(cleared,op);return false}catch{return true}})()",c);assert.equal(result,true);});
test('CSV mendukung koma dan baris baru dalam nama; kutip rusak ditolak',async()=>{const c=await context();assert.equal(vm.runInContext(`csvRows('nama,jumlah,kelompok\\n"Keluarga, A",2,B')[1][0]`,c),'Keluarga, A');assert.throws(()=>vm.runInContext(`csvRows('"tidak selesai')`,c));});
test('Cadangan terenkripsi dapat dibuka dengan sandi benar dan menolak sandi salah',async()=>{const c=await context();assert.equal(await vm.runInContext(`(async()=>{const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const k=await keyFor('ujicoba123',salt),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode('data tamu'));const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},await keyFor('ujicoba123',salt),encrypted);let rejected=false;try{await crypto.subtle.decrypt({name:'AES-GCM',iv},await keyFor('salah123',salt),encrypted);}catch{rejected=true;}return new TextDecoder().decode(plain)==='data tamu'&&rejected;})()`,c),true);});
test('QR buatan dapat dibaca kembali oleh jsQR',()=>{const qr=require('../dist/vendor/qrcode.js')(0,'M');const decode=require('../dist/vendor/jsQR.js');const value=JSON.stringify({v:1,event:'uji',code:'123456789'});qr.addData(value);qr.make();const scale=6,pad=4,n=(qr.getModuleCount()+pad*2)*scale,data=new Uint8ClampedArray(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const r=Math.floor(y/scale)-pad,c=Math.floor(x/scale)-pad,dark=r>=0&&c>=0&&r<qr.getModuleCount()&&c<qr.getModuleCount()&&qr.isDark(r,c),i=(y*n+x)*4;data[i]=data[i+1]=data[i+2]=dark?0:255;data[i+3]=255;}assert.equal(decode(data,n,n).data,value);});

test('Daftar tamu memisahkan nomor HP dan jumlah tanpa kode di nama',async()=>{const c=await context();vm.runInContext("db.guests=[{id:'g',code:'secret-qr',name:'Cesar',phone:'6281234567890',group:'OJK',quota:2,arrived:0,active:true}];document.querySelector('#search').value='';document.querySelector('#filter').value='all';renderGuests()",c);const html=vm.runInContext("document.querySelector('#guest-list').innerHTML",c);assert.match(html,/<td><strong>Cesar<\/strong><\/td><td>\+6281234567890<\/td><td>OJK<\/td><td>2 orang<\/td>/);assert.doesNotMatch(html,/secret-qr/);});

test('Ringkasan membedakan kuota orang aktif dari jumlah check-in',async()=>{const c=await context();const markup=vm.runInContext("(()=>{db.guests=[{id:'a',code:'a',name:'Aktif A',group:'',quota:2,arrived:1,active:true},{id:'b',code:'b',name:'Aktif B',group:'',quota:3,arrived:0,active:true},{id:'c',code:'c',name:'Nonaktif',group:'',quota:9,arrived:0,active:false}];document.querySelector('#filter').value='all';render();return document.querySelector('#stats').innerHTML})()",c);assert.match(markup,/Total undangan aktif<\/span><strong>2<small>undangan/);assert.match(markup,/Total orang diundang<\/span><strong>5<small>orang/);assert.match(markup,/Orang hadir<\/span><strong>1<small>orang/);});
test('WhatsApp tanpa nomor meminta nomor saja dan melanjutkan tanpa membuka Ubah',async()=>{
 const c=await context();
 await vm.runInContext("commit(d=>d.guests.push({id:'wa',code:'qr-tetap',name:'Tamu WhatsApp',phone:'',group:'Keluarga',quota:2,arrived:0,active:true}))",c);
 vm.runInContext("editGuest=()=>{throw Error('WhatsApp tidak boleh membuka Ubah');}",c);
 await vm.runInContext("showWhatsApp(db.guests[0],'https://example.com/invitation2#g=wa&k=key')",c);
 assert.equal(vm.runInContext("document.querySelector('#modal-title').textContent",c),'Nomor WhatsApp tamu');
 const html=vm.runInContext("document.querySelector('#modal-body').innerHTML",c);
 assert.match(html,/whatsapp-phone-form/);assert.doesNotMatch(html,/guest-form|Ganti QR/);
 vm.runInContext("document.querySelector('#whatsapp-phone').value='081234567890';var resumed=null;showWhatsApp=async(g,link)=>{resumed={guest:g,link};}",c);
 await vm.runInContext("document.querySelector('#whatsapp-phone-form').onsubmit({preventDefault(){},target:{querySelector(){return {disabled:false}}}})",c);
 assert.equal(vm.runInContext('db.guests[0].phone',c),'6281234567890');
 assert.equal(vm.runInContext('db.guests[0].code',c),'qr-tetap');
 assert.equal(vm.runInContext('resumed.guest.quota',c),2);
 assert.equal(vm.runInContext('resumed.link',c),'https://example.com/invitation2#g=wa&k=key');
});
test('Nomor WhatsApp tidak valid tidak mengubah data dan tidak membuka Ubah',async()=>{
 const c=await context();
 await vm.runInContext("commit(d=>d.guests.push({id:'wa',code:'qr',name:'Tamu WhatsApp',phone:'',group:'',quota:1,arrived:0,active:true}))",c);
 await vm.runInContext("showWhatsApp(db.guests[0])",c);
 vm.runInContext("document.querySelector('#whatsapp-phone').value='abc'",c);
 await vm.runInContext("document.querySelector('#whatsapp-phone-form').onsubmit({preventDefault(){},target:{querySelector(){return {disabled:false}}}})",c);
 assert.equal(vm.runInContext('db.guests[0].phone',c),'');
 assert.ok(vm.runInContext("document.querySelector('#whatsapp-phone-status').textContent.length",c)>0);
 assert.equal(vm.runInContext("document.querySelector('#modal-title').textContent",c),'Nomor WhatsApp tamu');
});
test('Dropdown kedatangan defaults to remaining quota and camera is retained after verification',async()=>{
 const c=await context();await vm.runInContext("commit(d=>d.guests.push({id:'drop',code:'qr',name:'Tamu',group:'',quota:3,arrived:0,active:true,akad:'y'}))",c);
 vm.runInContext("let stops=0;stream={active:true,getTracks:()=>[{stop(){stops++}}]};showGuest(db.guests[0]);",c);
 let html=vm.runInContext("document.querySelector('#modal-body').innerHTML",c);assert.ok(html.includes('<select id="count"'));assert.ok(html.indexOf('value="3"')<html.indexOf('value="2"'));assert.ok(html.indexOf('value="2"')<html.indexOf('value="1"'));assert.equal(vm.runInContext('stops',c),0);
 await vm.runInContext("checkIn('drop',2)",c);vm.runInContext('showGuest(db.guests[0])',c);html=vm.runInContext("document.querySelector('#modal-body').innerHTML",c);assert.ok(html.includes('value="1"'));assert.ok(!html.includes('value="2"'));vm.runInContext('stopCamera()',c);assert.equal(vm.runInContext('stops',c),1);
});
test('Scanner keeps scheduling frames and requires QR to leave view before reaccepting same code',async()=>{
 const c=await context();vm.runInContext(`let frames=0,hits=0,currentQr={data:'abc'};requestAnimationFrame=()=>frames++;jsQR=()=>currentQr;scanning=true;showGuest=()=>hits++;ctx.drawImage=()=>{};ctx.getImageData=()=>({data:[],width:1,height:1});Object.assign(document.querySelector('#video'),{readyState:2,videoWidth:100,videoHeight:100});document.querySelector('#modal').open=false;scan(200);scan(400);currentQr=null;scan(600);currentQr={data:'abc'};scan(800);`,c);
 assert.equal(vm.runInContext('hits',c),2);assert.equal(vm.runInContext('frames',c),4);
});

test('Pilihan massal membedakan semua, kelompok dan ID tamu tanpa menyertakan tamu dihapus',async()=>{const c=await context();vm.runInContext(`db.guests=[{id:'a',name:'Bayu',group:'OJK',active:true},{id:'b',name:'Bayu',group:'Keluarga CPP',active:true},{id:'c',name:'Citra',group:'OJK',active:false},{id:'d',name:'Tamu dihapus',group:'',active:false,deleted:true}];`,c);const select=(kind,mode,group,ids)=>JSON.parse(vm.runInContext(`JSON.stringify(bulkSelection(${JSON.stringify(kind)},${JSON.stringify(mode)},${JSON.stringify(group)},new Set(${JSON.stringify(ids)})).map(g=>g.id))`,c));assert.deepEqual(select('print','all','',[]),['a','b']);assert.deepEqual(select('akad','group','OJK',[]),['a','c']);assert.deepEqual(select('print','group','OJK',[]),['a']);assert.deepEqual(select('print','manual','',['b','d']),['b']);assert.deepEqual(select('akad','manual','',['b']),['b']);});
test('Perubahan akad massal menjaga QR, kuota, kehadiran dan hanya mengubah tamu terpilih',async()=>{const c=await context();await vm.runInContext(`commit(d=>d.guests.push({id:'a',code:'qa',name:'A',group:'OJK',quota:2,arrived:1,active:true,akad:'n'},{id:'b',code:'qb',name:'B',group:'OJK',quota:3,arrived:0,active:true,akad:'n'}))`,c);const before=JSON.parse(vm.runInContext('JSON.stringify(db.guests)',c));await vm.runInContext("updateAkad(['a'],'y')",c);const after=JSON.parse(vm.runInContext('JSON.stringify(db.guests)',c));before[0].akad='y';assert.deepEqual(after,before);await assert.rejects(vm.runInContext("updateAkad(['a'],'invalid')",c));await assert.rejects(vm.runInContext("updateAkad(['a','missing'],'n')",c));assert.equal(vm.runInContext("db.guests[0].akad",c),'y');});
test('Dialog cetak dan akad menampilkan tiga cara pilih serta menolak pilihan manual kosong',async()=>{const c=await context();await vm.runInContext(`commit(d=>d.guests.push({id:'a',code:'qa',name:'A',group:'OJK',quota:2,arrived:0,active:true,akad:'n'}))`,c);vm.runInContext("showBulkGuests('print')",c);let html=vm.runInContext("document.querySelector('#modal-body').innerHTML",c);assert.match(html,/Semua tamu/);assert.match(html,/Berdasarkan kelompok/);assert.match(html,/Pilih satu per satu/);vm.runInContext("document.querySelector('#bulk-mode').value='manual';document.querySelector('#bulk-mode').onchange()",c);assert.equal(vm.runInContext("document.querySelector('#bulk-submit').disabled",c),true);vm.runInContext("document.querySelector('#bulk-list').onchange({target:{dataset:{id:'a'},checked:true}})",c);assert.equal(vm.runInContext("document.querySelector('#bulk-submit').disabled",c),false);vm.runInContext("document.querySelector('#bulk-search').value='tidak cocok';document.querySelector('#bulk-search').oninput()",c);assert.match(vm.runInContext("document.querySelector('#bulk-summary').textContent",c),/^1 dari 1/);vm.runInContext("showBulkGuests('akad')",c);html=vm.runInContext("document.querySelector('#modal-body').innerHTML",c);assert.match(html,/Y — Tampilkan jam akad/);assert.match(html,/N — Family Only/);});

test('VIP massal menjaga status akad dan QR; perubahan kosong atau tidak valid ditolak',async()=>{const c=await context();await vm.runInContext(`commit(d=>d.guests.push({id:'a',code:'qa',name:'A',group:'OJK',quota:2,arrived:1,active:true,akad:'y'},{id:'b',code:'qb',name:'B',group:'Teman',quota:1,arrived:0,active:true,akad:'n'}))`,c);const before=JSON.parse(vm.runInContext('JSON.stringify(db.guests)',c));await vm.runInContext("updateVip(['a'],'y')",c);before[0].vip='y';assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(db.guests)',c)),before);await assert.rejects(vm.runInContext("updateVip(['a'],'yes')",c));await assert.rejects(vm.runInContext("updateVip([],'y')",c));await vm.runInContext("updateVip(['a'],'n')",c);assert.equal(vm.runInContext('db.guests[0].vip',c),'n');});
test('CSV menerima VIP y/n, default n pada CSV lama dan menolak nilai lain',async()=>{const c=await context();await vm.runInContext(`document.querySelector('#csv-file').onchange({target:{files:[{size:100,text:async()=> 'nama,jumlah,kelompok,vip\\nTamu VIP,2,OJK,Y'}]}})`,c);await vm.runInContext("document.querySelector('#confirm-import').onclick()",c);assert.equal(vm.runInContext('db.guests[0].vip',c),'y');await vm.runInContext(`document.querySelector('#csv-file').onchange({target:{files:[{size:100,text:async()=> 'nama,jumlah,kelompok\\nTamu Lama,1,Teman'}]}})`,c);await vm.runInContext("document.querySelector('#confirm-import').onclick()",c);assert.equal(vm.runInContext('db.guests[1].vip',c),'n');await vm.runInContext(`document.querySelector('#csv-file').onchange({target:{files:[{size:100,text:async()=> 'nama,jumlah,kelompok,vip\\nTamu Salah,1,Teman,yes'}]}})`,c);assert.equal(vm.runInContext('db.guests.length',c),2);vm.runInContext('let exportedCSV;download=(text)=>exportedCSV=text;',c);await vm.runInContext("document.querySelector('#export-csv').onclick()",c);assert.match(vm.runInContext('exportedCSV',c),/"akad","vip"/);assert.match(vm.runInContext('exportedCSV',c),/"n","y"/);});
test('VIP terlihat pada daftar dan check-in; tamu lama dianggap reguler',async()=>{const c=await context();await vm.runInContext(`commit(d=>d.guests.push({id:'a',code:'qa',name:'Tamu VIP',group:'OJK',quota:2,arrived:0,active:true,vip:'y'},{id:'b',code:'qb',name:'Reguler',group:'Teman',quota:1,arrived:0,active:true}))`,c);vm.runInContext("document.querySelector('#filter').value='all';renderGuests();showGuest(db.guests[0])",c);assert.match(vm.runInContext("document.querySelector('#guest-list').innerHTML",c),/role="switch" aria-checked="true" aria-label="VIP/);assert.match(vm.runInContext("document.querySelector('#modal-body').innerHTML",c),/Tamu VIP<\/span>/);vm.runInContext('showGuest(db.guests[1])',c);assert.doesNotMatch(vm.runInContext("document.querySelector('#modal-body').innerHTML",c),/vip-badge/);vm.runInContext("showBulkGuests('vip')",c);assert.match(vm.runInContext("document.querySelector('#modal-body').innerHTML",c),/Status VIP/);});

test('Toggle langsung menjaga QR dan menangkal perubahan stale',async()=>{const c=await context();await vm.runInContext(`commit(d=>d.guests.push({id:'a',code:'qa',name:'A',group:'OJK',quota:2,arrived:1,active:true,akad:'n',vip:'n'}))`,c);await vm.runInContext("toggleGuestFlag('a','vip',false)",c);await assert.rejects(vm.runInContext("toggleGuestFlag('a','vip',false)",c));await vm.runInContext("toggleGuestFlag('a','akad',false)",c);assert.equal(vm.runInContext('db.guests[0].code',c),'qa');assert.equal(vm.runInContext('db.guests[0].arrived',c),1);assert.equal(vm.runInContext('db.guests[0].vip',c),'y');assert.equal(vm.runInContext('db.guests[0].akad',c),'y');});
test('WhatsApp dibuka dan terkirim dicatat terpisah; pop-up diblokir tidak menandai dibuka',async()=>{const c=await context();await vm.runInContext(`commit(d=>d.guests.push({id:'a',code:'qa',name:'A',phone:'6281234567890',group:'OJK',quota:2,arrived:0,active:true}))`,c);vm.runInContext("TemuInvitations.qrFile=async()=>({name:'one.png'});window.open=()=>null;",c);await vm.runInContext("showWhatsApp(db.guests[0],'https://example.com/invitation2#g=a&k=key')",c);vm.runInContext("document.querySelector('#whatsapp-text').value='Undangan bersih';",c);await vm.runInContext("document.querySelector('#open-whatsapp').onclick()",c);assert.equal(vm.runInContext('db.guests[0].whatsappOpenedAt',c),undefined);vm.runInContext("let openedChat;window.open=()=>openedChat={location:{}};",c);await vm.runInContext("document.querySelector('#open-whatsapp').onclick()",c);assert.ok(vm.runInContext('db.guests[0].whatsappOpenedAt',c));assert.equal(vm.runInContext('db.guests[0].whatsappSentAt',c),undefined);assert.match(vm.runInContext('openedChat.location.href',c),/^https:\/\/wa.me\/6281234567890\?text=/);vm.runInContext("let copiedDraft;navigator.clipboard={writeText:async text=>copiedDraft=text};",c);await vm.runInContext("document.querySelector('#copy-invite').onclick()",c);assert.equal(vm.runInContext('copiedDraft',c),'Undangan bersih');await vm.runInContext("document.querySelector('#mark-whatsapp-sent').onclick()",c);assert.ok(vm.runInContext('db.guests[0].whatsappSentAt',c));assert.equal(vm.runInContext('whatsappStatus(db.guests[0])',c),'Sudah kirim WhatsApp');});

test('Filter kelompok bekerja bersama pencarian dan kehadiran serta mempertahankan pilihan',async()=>{const c=await context();await vm.runInContext(`commit(d=>d.guests.push({id:'a',code:'qa',name:'Bayu',group:'OJK',quota:2,arrived:1,active:true},{id:'b',code:'qb',name:'Bayu',group:'Keluarga',quota:2,arrived:0,active:true},{id:'c',code:'qc',name:'Citra',group:'',quota:1,arrived:0,active:true}))`,c);assert.equal(vm.runInContext("filteredGuests('bayu','some','g:OJK').length",c),1);assert.equal(vm.runInContext("filteredGuests('bayu','none','g:OJK').length",c),0);assert.equal(vm.runInContext("filteredGuests('','all','g:')[0].name",c),'Citra');vm.runInContext("document.querySelector('#filter').value='all';document.querySelector('#guest-group-filter').value='g:OJK';renderGuests()",c);assert.equal(vm.runInContext("document.querySelector('#guest-group-filter').value",c),'g:OJK');assert.match(vm.runInContext("document.querySelector('#guest-list').innerHTML",c),/data-id="a"/);assert.doesNotMatch(vm.runInContext("document.querySelector('#guest-list').innerHTML",c),/data-id="b"/);});
