const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process');const {IDBFactory}=require('fake-indexeddb');
const seed={version:1,event:{id:'integration',name:'Acara Uji',date:''},guests:[{id:'g',code:'qr',name:'Tamu Uji',group:'',quota:2,arrived:0,active:true}],logs:[],pin:null};
function browser(base,network){const elements=new Map(),el=()=>({value:'',hidden:false,textContent:'',innerHTML:'',classList:{toggle(){}},contains(){return false},getContext(){return{}},showModal(){},close(){},addEventListener(){}});const c=vm.createContext({indexedDB:new IDBFactory(),crypto:require('node:crypto').webcrypto,structuredClone,TextEncoder,TextDecoder,Uint8Array,Date,Set,JSON,console,AbortSignal,fetch:(url,opts)=>network(base+url,opts),setTimeout:()=>0,clearTimeout(){},setInterval(){},alert(){},document:{querySelector(s){if(!elements.has(s))elements.set(s,el());return elements.get(s)},querySelectorAll(){return[]},createElement:el,addEventListener(){}},window:{addEventListener(){}},navigator:{},localStorage:{getItem(){return JSON.stringify(seed)}},btoa,atob});for(const f of ['sync-model.js','storage.js','invitations.js','app.js','sync.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/'+f),'utf8'),c);return c;}
test('offline queue survives lost server response and retries exactly once; second device sees conflict',async()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'temu-integration-'));const code="import sys;sys.path.insert(0,'server');from server import *;d=Database(sys.argv[1]);s=ThreadingHTTPServer(('127.0.0.1',0),make_handler(d,'t'*40,{'127.0.0.1'}));print(s.server_port,flush=True);s.serve_forever()";
 const server=spawn('python3',['-c',code,directory],{cwd:path.join(__dirname,'..'),stdio:['ignore','pipe','pipe']});let errors='';server.stderr.on('data',x=>errors+=x);
 try{const port=await new Promise((resolve,reject)=>{server.stdout.once('data',x=>resolve(Number(x.toString().trim())));server.once('exit',()=>reject(Error(errors)));});const base='http://127.0.0.1:'+port;let offline=false,loseResponse=false;
 const a=browser(base,async(url,opts)=>{if(offline)throw TypeError('offline');const r=await fetch(url,opts);if(loseResponse&&url.endsWith('/api/sync')){loseResponse=false;await r.text();throw TypeError('connection lost');}return r;});
 await vm.runInContext('applicationReady',a);await vm.runInContext('syncNow()',a);assert.equal((await a.TemuStore.read()).outbox.length,0);
 const b=browser(base,(url,opts)=>fetch(url,opts));await vm.runInContext('applicationReady',b);await vm.runInContext('syncNow()',b);
 offline=true;await vm.runInContext("checkIn('g',1)",a);await vm.runInContext('syncNow()',a);assert.equal((await a.TemuStore.read()).outbox.length,1);assert.equal((await a.TemuStore.read()).state.guests[0].arrived,1);
 offline=false;loseResponse=true;await vm.runInContext('syncNow()',a);assert.equal((await a.TemuStore.read()).outbox.length,1);await vm.runInContext('syncNow()',a);assert.equal((await a.TemuStore.read()).outbox.length,0);
 await vm.runInContext("checkIn('g',1)",b);await vm.runInContext('syncNow()',b);const second=await b.TemuStore.read();assert.equal(second.state.guests[0].arrived,1);assert.ok(second.conflicts.some(c=>c.op.kind==='change'));assert.equal(second.state.logs.length,1);assert.ok(second.serverBackupAt);
 }finally{server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));fs.rmSync(directory,{recursive:true,force:true});}
});
