const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');const {IDBFactory}=require('fake-indexeddb');
function environment(factory=new IDBFactory()){const c=vm.createContext({indexedDB:factory,crypto:require('node:crypto').webcrypto,structuredClone,console});for(const f of ['sync-model.js','storage.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/'+f),'utf8'),c);return c;}
function seed(){return {version:1,event:{id:'event',name:'Uji',date:''},guests:[{id:'g',code:'q',name:'Tamu',quota:2,arrived:0,active:true,group:''}],logs:[],pin:null};}
test('state and outbox survive reload together; snapshots rotate',async()=>{const factory=new IDBFactory(),c=environment(factory);await c.TemuStore.init(seed);for(let i=0;i<25;i++)await c.TemuStore.mutate(s=>s.event.name='Nama '+i,()=>{});const next=environment(factory),r=await next.TemuStore.read();assert.equal(r.state.event.name,'Nama 24');assert.equal(r.outbox.length,26);assert.equal(r.backups.length,20);});
test('failed validation does not change state or outbox',async()=>{const c=environment();await c.TemuStore.init(seed);await assert.rejects(c.TemuStore.mutate(s=>{s.event.name='bad';},()=>{throw Error('bad');}));const r=await c.TemuStore.read();assert.equal(r.state.event.name,'Uji');assert.equal(r.outbox.length,1);});
test('concurrent tabs serialize mutations instead of losing updates',async()=>{const factory=new IDBFactory(),a=environment(factory),b=environment(factory);await a.TemuStore.init(seed);await Promise.all([a.TemuStore.mutate(s=>s.guests[0].arrived++,()=>{}),b.TemuStore.mutate(s=>s.guests[0].arrived++,()=>{})]);const r=await a.TemuStore.read();assert.equal(r.state.guests[0].arrived,2);assert.equal(r.outbox.length,3);});
test('in-flight local changes rebase onto server result',()=>{const c=environment(),before=seed(),after=structuredClone(before);after.guests[0].arrived=1;const op=c.TemuModel.operation(before,after);const remote=structuredClone(before);remote.event.name='Pengaturan baru';const r=c.TemuModel.rebase(remote,[op]);assert.equal(r.state.guests[0].arrived,1);assert.equal(r.state.event.name,'Pengaturan baru');assert.equal(r.conflicts.length,0);});
test('overlapping changes preserved as conflicts, never silently counted twice',()=>{const c=environment(),before=seed(),after=structuredClone(before);after.guests[0].arrived=1;const op=c.TemuModel.operation(before,after),r=c.TemuModel.rebase(after,[op]);assert.equal(r.state.guests[0].arrived,1);assert.equal(r.conflicts.length,1);assert.equal(r.conflicts[0].op.id,op.id);});
test('local backup restore keeps audit history and queues synchronization',async()=>{const c=environment();await c.TemuStore.init(seed);await c.TemuStore.mutate(s=>{s.guests[0].arrived=1;s.logs.push({id:'log',guest:'g',count:1,at:new Date().toISOString()});},()=>{});const r=await c.TemuStore.replace(seed(),()=>{});assert.equal(r.state.guests[0].arrived,0);assert.equal(r.state.logs.length,2);assert.equal(r.outbox.length,3);});
